<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <!--Nuget-->
  <PropertyGroup>
    <PackageId>Cronus.Persistence.Cassandra</PackageId>

    <Product>Cronus</Product>
    <Title>Cronus</Title>
    <Description>Cronus is a lightweight framework for building event driven systems with DDD/CQRS in mind.</Description>
    <PackageTags>CQRS DDD ES Event store sourcing cronus</PackageTags>

    <Copyright>Copyright © Elders LTD 2026</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RequireLicenseAcceptance>true</RequireLicenseAcceptance>

    <PackageIconUrl>https://raw.githubusercontent.com/Elders/logo/master/cronus/frame.png</PackageIconUrl>
    <RepositoryUrl>https://github.com/Elders/Cronus.git</RepositoryUrl>
    <PackageProjectUrl>https://github.com/Elders/Cronus</PackageProjectUrl>
    <RepositoryType>git</RepositoryType>

    <AssemblyName>Elders.Cronus.Persistence.Cassandra</AssemblyName>
    <RootNamespace>Elders.Cronus.Persistence.Cassandra</RootNamespace>
    <NeutralLanguage>en-US</NeutralLanguage>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AssemblyVersion>11.0.0</AssemblyVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cronus" Version="11.2.5" />
    <PackageReference Include="CassandraCSharpDriver" Version="3.22.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.7" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Elders.Cronus.Persistence.Cassandra.Integration.Tests" />
  </ItemGroup>
</Project>
