// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Elders.Cronus.Persistence.Cassandra")]
[assembly: AssemblyDescriptionAttribute("Elders.Cronus.Persistence.Cassandra")]
[assembly: AssemblyProductAttribute("Elders.Cronus.Persistence.Cassandra")]
[assembly: AssemblyVersionAttribute("2.0.0")]
[assembly: AssemblyInformationalVersionAttribute("2.0.0")]
[assembly: AssemblyFileVersionAttribute("2.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "2.0.0";
    }
}
