// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Elders.Cronus.Persistence.Cassandra")]
[assembly: AssemblyDescriptionAttribute("Elders.Cronus.Persistence.Cassandra")]
[assembly: AssemblyProductAttribute("Elders.Cronus.Persistence.Cassandra")]
[assembly: AssemblyVersionAttribute("1.1.0")]
[assembly: AssemblyInformationalVersionAttribute("1.1.0")]
[assembly: AssemblyFileVersionAttribute("1.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.1.0";
    }
}
